---
title: "A1_54007301"
author: "540007301"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    code-tools: true
    code-fold: true
    fig_caption: yes
    number_sections: yes
    embed-resources: true
    theme: flatly
    toc: true
    toc_depth: 4
    toc_float: true
execute:
  echo: true
  tidy: true
---
```{r loadpackages, message=FALSE, warning=FALSE}
library(Biobase)
library(limma)

theme_set(theme_bw())
x = readxl::read_excel(here("assignment", "DATA2x02_survey_2025_Responses.xlsx"))
knitr::write_bib(c(.packages(),
                   "knitr", "rmarkdown"), "report.bib")


```


## Introduction.

ATODE

# Part 1: Exploratory Analysis


```{r}
load("GSE138043.RData")
gse138043 <- gse

load("GSE46474.RData")
gse46474 <- gse

expr1 <- exprs(gse138043)
pd1 <- pData(gse138043)
fd1 <- fData(gse138043)

expr2 <- exprs(gse46474)
pd2 <- pData(gse46474)
fd2 <- fData(gse46474)
```

```{r}
extract_symbols_fd1 <- function(x) {
  if (is.na(x) || x == "") return(character(0))
  
  parts <- unlist(strsplit(x, " /// "))
  
  syms <- vapply(parts, function(part) {
    fields <- unlist(strsplit(part, " // "))
    if (length(fields) >= 2) fields[2] else NA_character_
  }, character(1))
  
  syms <- unique(na.omit(syms))
  syms <- syms[syms != ""]
  syms
}

extract_unique_symbol_fd1 <- function(x) {
  syms <- extract_symbols_fd1(x)
  if (length(syms) == 1) syms else NA_character_
}

extract_symbols_fd2 <- function(x) {
  if (is.na(x) || x == "") return(character(0))
  
  parts <- unlist(strsplit(x, " /// "))
  parts <- trimws(parts)
  parts <- unique(parts)
  parts <- parts[parts != ""]
  parts
}


extract_unique_symbol_fd2 <- function(x) {
  syms <- extract_symbols_fd2(x)
  if (length(syms) == 1) syms else NA_character_
}
```



```{r}
#gse138043

group1 <- factor(pd1[["rejection at 12months post transplant:ch1"]])
group1_clean <- factor(make.names(as.character(group1)))

table(group1_clean)

design1 <- model.matrix(~ 0 + group1_clean)
colnames(design1) <- levels(group1_clean)

fit1 <- lmFit(expr1, design1)
cont1 <- makeContrasts(AR - non.AR, levels = design1)
fit1 <- contrasts.fit(fit1, cont1)
fit1 <- eBayes(fit1)

res1 <- topTable(fit1, number = Inf, adjust.method = "BH")

res1$GeneSymbol <- vapply(
  fd1[rownames(res1), "gene_assignment"],
  extract_unique_symbol_fd1,
  character(1)
)

res1_clean <- res1[!is.na(res1$GeneSymbol) & res1$GeneSymbol != "", ]

res1_clean <- res1_clean[order(res1_clean$adj.P.Val, -abs(res1_clean$logFC)), ]

res1_unique <- res1_clean[!duplicated(res1_clean$GeneSymbol), ]

top20_table1 <- res1_unique[1:20, c("GeneSymbol", "logFC", "adj.P.Val", "P.Value", "t", "B")]
top20_table1

```

```{r}
#gse46474 

group2 <- factor(pd2[["procedure status:ch1"]])
group2_clean <- factor(make.names(as.character(group2)))

table(group2_clean)

design2 <- model.matrix(~ 0 + group2_clean)
colnames(design2) <- levels(group2_clean)

fit2 <- lmFit(expr2, design2)
cont2 <- makeContrasts(
  post.transplant.acute.rejection..AR. - post.transplant.non.rejection..NR.,
  levels = design2
)
fit2 <- contrasts.fit(fit2, cont2)
fit2 <- eBayes(fit2)

res2 <- topTable(fit2, number = Inf, adjust.method = "BH")

res2$GeneSymbol <- vapply(
  fd2[rownames(res2), "Gene Symbol"],
  extract_unique_symbol_fd2,
  character(1)
)
res2_clean <- res2[!is.na(res2$GeneSymbol) & res2$GeneSymbol != "", ]

res2_clean <- res2_clean[order(res2_clean$adj.P.Val, -abs(res2_clean$logFC)), ]

res2_unique <- res2_clean[!duplicated(res2_clean$GeneSymbol), ]

top20_table2 <- res2_unique[1:20, c("GeneSymbol", "logFC", "adj.P.Val", "P.Value", "t", "B")]
top20_table2
```


```{r}
#the below shows that the data is continuouys and roughly log-scale. This means that the datasets are clean, and thus the use of limma is appropriate for differential expression method. However for gse138043, due to the imbalance in AR and non-AR the power of the analysis may be affected.

summary(as.vector(expr1))
summary(as.vector(expr2))

boxplot(expr1, las = 2, main = "GSE138043 (biopsy-based)")
boxplot(expr2, las = 2, main = "GSE46474 (blood-based)")
```

```{r}
boxplot(expr1, las = 2, main = "GSE138043")
boxplot(expr2, las = 2, main = "GSE46474")

#あとでqqplot足す
```

```{r}
top20_1 <- top20_table1$GeneSymbol
top20_2 <- top20_table2$GeneSymbol

overlap_genes <- intersect(top20_1, top20_2)
biopsy_only    <- setdiff(top20_1, top20_2)
blood_only     <- setdiff(top20_2, top20_1)

overlap_genes
biopsy_only
blood_only
length(overlap_genes)
```



